### ISSUE TITLE
crash in Tokiria Forest after Hero's Tomb sequence of events

### ISSUE THREAD

**Issue by xMitsu3** [krm01/oot-indigo-mod#16]
Tried to find a discord or something and i couldn't so i decided i'd post this here. Anyway, after doing the Hero's Tomb sequence of events (and defeating her because i have no heart) i went back to the shop to see what would happen, basically there was another ''Item Satchel'' on sale, tried buying it, and got a crash. Unsure if the item is not intended to be there, since it's not there before doing the Hero's Tomb, or if it simply crashed (playing on Project 64 3.0.1). You can still hear the music and it's a bunch of different screens which all have numbers and stuff like this. 
![Fv9QjyvWIAA_vrH](https://github.com/krm01/oot-indigo-mod/assets/97474745/4ded87ee-9d56-4338-b5ff-ac414a98e685)

**Comment by krm01** [comment]
Thanks for this - I'll copy it over to our main dev repo, not sure what's going on but we'll get it fixed someday. thank you!!

**Comment by krm01** [comment]
resolved in the new 0.3.16 version
