### ISSUE TITLE
Z-Targeting Stuck On

### ISSUE THREAD

**Issue by DamianSuess** [krm01/oot-indigo-mod#17]
Running into an issue where Z targeting is stuck on. I tried hopping on to discord, but it won't accept the invite from what is published in the Github Releases area.

Build: 0.3.15-fe424834

Reproduce:
* Tap Z
* Or, throw the boomerang

Workaround:
* Hold Z and press Start
* Let go of Z
* Press Start again unpause the game

P.s. can't thank you enough for creating this mod. It brings new life to the game, has to be my absolute favorite right now.

**Comment by krm01** [comment]
Thanks for reporting! I think I fixed the discord link on the release page, sorry about that! So I'm having trouble reproducing the problem. You say you can just tap Z and you'll get stuck in the Z-targeting mode, even without any enemies around that you're locked on to?

What platform are you playing on (N64, Wii VC, emulator? which emulator, which version etc?)

**Comment by DamianSuess** [comment]
Came back this morning to get the info and it's working just fine again. Totally strange.

Just as an FYI:

* Hardware: Raspberry Pi 4
* OS: RecalBox v9.1
* Emulator: Mupen64Plus Glide64MK2

Keep up the great work, I love this mod!

**Comment by DamianSuess** [comment]
@krm01 just finished playing the game and all I can say is, WOW!!

I wish the original game had these mechanics and difficulty. It was such a joy of nostalgia and puzzle solving.  Thank you!
