### ISSUE TITLE
What are the gzinject codes to map the N64 L button and D-Pad buttons on a Wii Classic Controller?

### ISSUE THREAD

**Issue by sdw4938** [krm01/oot-indigo-mod#3]
I looked everywhere but I couldn't find any of the gzinject codes (or whatever they are called) to allow the L button and D-Pad buttons to be mapped to the Wii Classic Controller. So, I thought I'd ask here.
Pressing D-Pad down to use the extra C-Button slots doesn't do anything and using any of the D-Pad buttons in the Pause Menu just scrolls left. Furthermore, the N64 L button isn't mapped to any of the buttons on the Wii Classic Controller. 
I don't think this is an issue with the Romhack but rather an issue with the Wii VC emulator.

Also, I watched a video on this Romhack and so far, it looks amazing. I am very excited to play this!

**Comment by krm01** [comment]
Oh jeez, sorry, I wish I could be more help here but I really don't know a whole lot about Wii VC and gzinject. I think maybe you could try the remapping patches here?

https://github.com/glankk/gz/tree/master/gzi

That's the only thing I can point you to.. wish I could be more helpful.

If one of those works or you do come across it, let me know and I'll update the release template for future releases to include it for others 👍

**Comment by sdw4938** [comment]
I found the D-Pad remapping code. Taken from the gz.gzi file.
```
# Apply Dpad remappings
0302 0016BAF0 00000800
0302 0016BAF4 00000400
0302 0016BAF8 00000200
0302 0016BAFC 00000100
```
I'm still looking for the code to map the L button to the Wii Classic Controller.

**Comment by krm01** [comment]
I've found the codes, the current v0.1.10 release (and all future releases) will include them.
