### ISSUE TITLE
Demo feedback

### ISSUE THREAD

**Issue by LuigiXHero** [krm01/oot-indigo-mod#4]
My brother who plays rando with me a lot but otherwise doesn't play ocarina played this recently and had some thoughts:
He thought the tektites at the start do way too much damage and he had trouble fighting them even with the flame hint.
He also thinks in skyloft ruins the central spinning platform is way too fast and nearly quit the game over constantly missing his jumps. My suggestion is maybe keep it as is for the deku light puzzle but slow it down after.

**Comment by krm01** [comment]
noted!! thanks a lot. I'll look into adjusting the bridge.
