### ISSUE TITLE
Weird punctuation while talking with Naffige for the first time

### ISSUE THREAD

**Issue by adiabatic** [krm01/oot-indigo-mod#5]
I'm watching [Zfg1 play](https://www.twitch.tv/videos/1809781584) a then-soon-to-be-released version of Indigo. I noticed some weird punctuation when talking to Naffige for the first time, at around 12013 seconds into the video.

Here's what the screen looks like:

> ###### Naffige, The Occulyte
> 
> Greetings friend. What brings you here? 
> My name is Naffige, I'm a devout 
> researcher of the Scar.

"My name is Naffige" and "I'm a devout researcher of the Scar" are two independent clauses, so they really ought to be [separated by something other than just a comma](https://www.grammarly.com/blog/comma-splice/). Even if the mod is being done in [elocutionary punctuation instead of syntactic](http://esr.ibiblio.org/?p=1024), I'm still having trouble imagining someone saying those two things with only a comma-duration pause in between, just like I have trouble imagining someone saying "Greetings friend" _without_ at least a comma-level pause in between.

Doubly so since Naffige doesn't seem like a particularly breathless guy, especially when the subject of what he wants you to collect comes up. The long piles of ellipses that he uses to convey loooong pauses; I wouldn't expect a fast-talker to pause _that_ much for a subject like that.

As for the changes I'd recommend:

- Change `Greetings friend` to `Greetings, friend`
- Change `My name is Naffige, I'm a` to one of:
  - `My name is Naffige; I'm a`
  - `My name is Naffige — I'm a`
  - `My name is Naffige—I'm a`
  - `My name is Naffige. I'm a`

…although I don't know if OoT has a good em dash available in its font.

--------

Additionally I noticed at least one typo earlier in the stream, possibly a misspelling of "endeavor". If you'd be interested in further reports of either misspellings and/or grammar nitpicks, please let me know either way. Thanks!

**Comment by krm01** [comment]
hey thanks for this! I'll get this corrected in the next patch. it's small but typos can really take you out of the moment ya know, so I appreciate the report!

**Comment by krm01** [comment]
closed the reported issues, they have been fixed on the dev repo. thanks for all the effort reporting these, greatly greatly appreciated!
